# Basic site settings
locale: "en-US"
title: "Abdullah Mansour"
description: "Abdullah Mansour's academic portfolio"
url: "https://abdullah0803-cpu.github.io"
baseurl: ""
repository: "abdullah0803-cpu/abdullah0803-cpu.github.io"

# Theme
site_theme: "default"

# Author (sidebar)
author:
  name: "Abdullah Mansour"
  avatar: "1757281832425.png"
  bio: "Student at University of Houston"
  location: "Houston, TX"
  employer: "University of Houston"
  email: "abdullah0803@hotmail.com"
  github: "AbdullahMansour01"
  linkedin: "abdullah-mansour-54843229"

# Build behavior
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Etc/UTC

# Files
include:
  - _pages
  - files

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yaml
  - package.json*
  - README
  - scripts
  - markdown_generator
  - talkmap*
  - *.ipynb

# Plugins (GitHub Pages safe)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
